spring:
  profiles:
    active: dev
  application:
    name: passenger

  main:
    allow-circular-references: false

  mvc:
    problemdetails:
      enabled: true

  data:
    mongodb:
      uri: ${MONGODB_PASSENGER_URI:mongodb://localhost:27017/passenger_read}
      database: ${MONGODB_PASSENGER_DB:passenger_read}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PASS:guest}
    template:
      exchange: passenger
      exchange-type: fanout

  otel:
    collector:
      service-name: passenger
      service-version: 1.0.0
      endpoint: http://localhost:4317

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/keycloak-realm/protocol/openid-connect/certs
